### ISSUE TITLE
Getting: "This document <document path> is not an ARM Template

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [wilfriedwoivre/vscode-arm-params-generator#1]
Hi,

I have got an ARM Template for an API Management setup. When I click on generate properties file I got the error:

![image](https://user-images.githubusercontent.com/6192200/48356292-3b596f80-e696-11e8-9f8b-6b5e6170caf1.png)

I don't think there is anything wrong with the ARM template. Is there something else that could be an issue?

**Comment by wilfriedwoivre** [comment]
Hi,

Thanks for your feedback.

Which version of ARM Extension do you use ?

In your ARM file, do you have any comments ? 
I've a know issue with single line JSON comment. With the last version, you can use multilines comments in JSON like: /* my comment */

This feature actually use file on disk, you must save your file and validate if your JSON file is correct with an online parser like: [http://json.parser.online.fr/](http://json.parser.online.fr/) (extra or missing comma is a common error with ARM Template)

**Comment by SoucianceEqdamRashti** [comment]
I am using the latest version.

I don't have any comments and it is correctly parsed in the online parser. The ARM template in this case is one for API Management. It is a bit hard to know which part it does not like.

**Comment by SoucianceEqdamRashti** [comment]
By the way I also used an ARM templates from one of the quickstart tutorials from Azure and got the same problem there. It was a template to create a VM.

**Comment by wilfriedwoivre** [comment]
Thanks, 

i think i've found the bug, i push a new version of my extension tomorrow. 

You can fix the bug on your template with change on schema. 
You can use https url for the schema and not the http url like some template.

**Comment by wilfriedwoivre** [comment]
I push and deploy a version 0.6.0 with this bug fix. 

Let me know if this version solve your bug.

**Comment by SoucianceEqdamRashti** [comment]
Thanks for the quick update. Unfortunately I still get the same error. If ever you have time I can show my ARM template via skype or similar and the error. I cannot post it here for security reasons.  By the way the schema I use is:
`"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",`

**Comment by wilfriedwoivre** [comment]
Yes, we can check your arm template via a skype meeting. 

Send me a mail 'wilfried.woivre gmail.com' to find an availibility.

**Comment by mtnrbq** [comment]
I was getting the same error.
I removed the '#' from the end of the $schema name in the template
"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json"
I was then able to generate the parameters file without an error, and then I could just put the # back in.

Hope this helps

**Comment by wilfriedwoivre** [comment]
Hi, 

The last version (0.6.0) verify if schema contains **"schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json"**

I currently test new json parser to improve this error message.
